# authors_prose = ["Čapek, K.","Čapek, K.","Drda, J.","Dyk, V.","Olbracht, I.","Páral, V.","Pavel, O.","Šabach, P.","Škvorecký, J.","Šrámek, F.","Vančura, V.","Viewegh, M.","Fuks, L.","Hrabal, B.","Hrabal, B.","Jirotka, Z.","Kafka, F.","Kafka, F.","Kundera, M.","Kundera, M.","Poláček, K.","Asimov, I. robot,","Bradbury, R.","Camus, A.","Capote, T.","Eco, U.","Exupéry, A. de Saint","Franková, A.","Golding, W.","Heller, J.","Hemingway, E.","Christie, A.","Irving, J.","Kerouac, J.","Kesey, K.","King, S.","King, S.","London, J.","Nabokov, V. V.","Orwell, G.","Orwell, G.","Remarque, E. M.","Rolland, R.","Salinger, J. D.","Solženicyn, A.","Steinbeck, J.","Styron, W.","Tolkien, J.R.R.","Wyndham, J.","Moravia, A.","Čech, Sv. tentokráte do XV.století,","Dickens, Ch.","Arbes, J.","Balzac, H.","Hugo, V.","Maupassant, G.","Neruda, J.","Poe, E. A.","Puškin, A. S.","Rais, K. V.","Dostojevskij, F. M.","Nezval, V.","Goethe, J. W.",]
# titles_prose ["Krakatit", "Válka s mloky", "Němá barikáda", "Krysař", "Nikola Šuhaj loupežník", "Mladý muž a bílá velryba", "Smrt krásných srnců", "Občanský průkaz", "Zbabělci", "Stříbrný vítr", "Rozmarné léto", "Báječná léta pod psa", "Spalovač mrtvol", "Obsluhoval jsem anglického krále", "Ostře sledované vlaky", "Saturnin", "Proces", "Proměna", "Nesnesitelná lehkost bytí", "Směšné lásky", "Bylo nás pět", "Já, robot", "451 stupňů Fahrenheita", "Cizinec", "Chladnokrevně", "Jméno růže", "Malý princ", "Deník Anne Frankové", "Pán much", "Hlava XXII.", "Stařec a moře", "Vražda v Orient expresu", "Svět podle Garpa", "Na cestě", "Vyhoďme ho z kola ven", "Misery", "Osvícení", "Tulák po hvězdách", "Lolita", "1984", "Farma zvířat", "Na západní frontě klid", "Petr a Lucie", "Kdo chytá v žitě", "Jeden den Ivana Děnisoviče", "O myších a lidech", "Sophiina volba", "Společenstvo prstenu", "Den trifidů", "Horalka", "Nový epochální výlet pana Broučka, tentokráte do XV.století", "Nadějné vyhlídky", "Svatý Xaverius", "Otec Goriot", "Chrám Matky Boží v Paříži", "Kulička", "Povídky malostranské", "Jáma a kyvadlo", "Piková dáma", "Kalibův zločin", "Zločin a trest", "Manon Lescaut", "Utrpení mladého Werthera"]
# authors_drama = ["Havel, V.","Smoljak, L., Svěrák, Z.","Čapek, K.","Čapek, K.","Čapek, K.","Voskovec, J., Werich, J.","Beckett, S.","Shaw, G. B.","Mrštíkové, A. a V.","Vrchlický, J.","Neznámý", "Molière","Shakespeare, W.","Shakespeare, W.","Shakespeare, W.","Shakespeare, W.","Sofokles",]
# titles_drama = ["Audience", "Vyšetřování ztráty třídní knihy", "Bílá nemoc", "Věc Makropulos", "Loupežník", "Balada z hadrů", "Čekání na Godota", "Pygmalion", "Maryša", "Noc na Karlštejně","Mastičkář", "Lakomec", "Hamlet", "Romeo a Julie", "Othello", "Zkrocení zlé ženy", "Antigona"]
authors_poetry = ["Gellner, F.","Hrabě, V.","Hrubín, F.","Kainar, J.","Kryl, K.","Seifert, J.","Žáček, J.","Erben, K. J.","Havlíček Borovský, K.","Havlíček Borovský, K.","Mácha, K. H.","Neruda, J.","Baudelaire, Ch.","Neznámý", "Villon, F."]
titles_poetry = ["Radosti života", "Blues pro bláznivou holku", "Romance pro křídlovku", "Nové mýty", "Kníška Karla Kryla", "Na vlnách TSF", "Okurková sezóna", "Kytice", "Křest svatého Vladimíra", "Tyrolské elegie", "Máj", "Balady a romance", "Květy zla", "Podkoní a žák", "Malý testament"]
years = [1924, 1936, 1946, 1939, 1933, 1973, 1971, 2006, 1948, 1910, 1926, 1992, 1967, 1971, 1965, 1942, 1925, 1915, 1984, 1967, 1943, 1950, 1953, 1942, 1966, 1980, 1943, 1947, 1954, 1961, 1953, 1935, 1978, 1957, 1962, 1987, 1977, 1915, 1955, 1949, 1945, 1929, 1920, 1960, 1962, 1937, 1979, 1954, 1951, 1957, 1888, 1861, 1873, 1835, 1831, 1880, 1878, 1842, 1834, 1892, 1866, 1731, 1774, 1975, 1967, 1937, 1922, 1920, 1935, 1952, 1912, 1894, 1884, '14. stol.', 1668, 1601, 1595, 1622, 1594, 'antika', 1903, 1990, 1961, 1946, 1960, 1925, 1982, 1853, 1877, 1861, 1836, 1883, 1857, "14. stol.", 1456]
title_type = "Poezie"
for count, year in enumerate(years):
    print(f"UPDATE tituly SET rok_vydani = '{year}' WHERE book_id = {count+3};")

# UPDATE tituly_test
# SET rok_vydani = '432'
# WHERE book_id = 5;